alias gs="git status -s -b"
alias lg="log --oneline --decorate  --all --graph"
alias gco="git checkout"
alias p="pwd"
alias gp="git pull"
alias gpom="git pull origin master"
alias l="ls -lah"
alias p="pwd"